---

- name: Download web
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  tags: without-postgres

- name: Install pgsql
  yum:
    name: postgresql14-server
  tags: without-postgres

# - name: install pip
#   yum:
#     name: 
#       - install epel-release
#       - install python-pip
#   tags: install-pip

# - name: install modules
#   yum:
#     name: 
#       - groupinstall "Development Tools"
#       - install python3-devel
#       - install postgresql-libs
#       - install postgresql-devel
#   tags: install-modules-pc2

# - name: install pc2
#   yum:
#     name: 
#       - python-psycorg2
#   tags: install-psycorg

- name: Ensure PostgreSQL database is initialized.
  shell: "/usr/pgsql-14/bin/initdb -D /var/lib/pgsql/14/data"
  become_user: postgres
  become: yes
  tags: skip-init

- name: WAL
  file: path=/wal state=directory owner=postgres group=postgres

- name: MODE-wal
  ansible.builtin.file:
    path: /wal
    state: directory
    recurse: yes
    owner: postgres
    group: postgres


- name: MODE-var/lib/pgsql
  ansible.builtin.file:
    path: /var/lib/pgsql/14/data/
    state: directory
    recurse: yes
    owner: postgres
    group: postgres
  tags: mode-data

# - name: Pg_hba-config
#   community.general.postgresql_pg_hba:
#     dest: /var/lib/pgsql/14/data/pg_hba.conf
#     contype: host
#     users: replication
#     source: 192.168.11.0/24
#     databases: all
#     method: trust
#   notify:
#     - restart postgres
#   tags: pg_hba

- name: pg_hba-config
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/14/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0600'
  notify:
    - restart postgres 
  tags: pg_hba

- name: postgres-config
  copy:
    src: postgresql.conf
    dest: /var/lib/pgsql/14/data/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0600'
  notify:
    - restart postgres 

- name: Reload config
  systemd:
    name: postgresql-14.service
    state: restarted
    enabled: yes